export const routes = {
  archive: "/mail/archive/",
  bookmarks: "/mail/bookmarks/",
  compose: "/mail/compose/",
  contacts: "/contacts/",
  drafts: "/mail/drafts/",
  editContact: "/contacts/edit/",
  editFolders: "/folders/edit/",
  folders: "/folders/",
  inbox: "/mail/inbox/",
  loginWallet: "/auth/wallet/",
  mail: "/mail/",
  main: "/",
  registration: "/auth/password/",
  sent: "/mail/sent/",
  settings: "/settings/",
  signature: "/settings/signature/",
  theme: "/settings/theme/",
};
